services:
  - type: web
    name: appreciators-tcg-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
